# Generated by Django 4.2 on 2023-05-01 10:59

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_decima_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='hola', max_length=50, unique=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='img',
            field=models.ImageField(default=11, upload_to=apps.products.models.ProductModel.url_generator, verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
