# Generated by Django 4.2 on 2023-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_description_productmodel_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.BooleanField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(max_length=50, unique=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio'),
        ),
    ]
